[pytest]
addopts = --strict-markers
markers =
    slow: Slow tests (likely from training)
filterwarnings =
    ignore::DeprecationWarning:mlagents_envs.communicator_objects
    ignore::torch.jit.TracerWarning:torch.nn.modules.rnn
